apiVersion: apps/v1
kind: Pod
metadata:
  name: yolo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      name: yolo-app
      labels:
        app: yolo-app
        role: frontend-backend
        env: prod
    spec:
      containers:
      - name: backend
        image: zaktales/yolo-backend:v1.0.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: backend
          containerPort: 5000
      - name: frontend
        image: zaktales/yolo-client:v1.0.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:  
    metadata:
      labels:
        app: mongodb        
    spec:
      containers:     
      - image: mongo:latest
        name: mongodb       
        ports:
        - containerPort: 27017      
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/db
          name: general-disk
          subPath: mongodb/data
        env:
        - name: MONGO_INITDB_DATABASE
          value: "yolomy"
        resources:
          limits:
            memory: "520Mi"
            cpu: "0.3"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
      - name: general-disk
        persistentVolumeClaim:
          claimName: general-disk          
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  type: LoadBalancer  
  selector:
    app: mongodb