version: '3.1'
services:
  server:
    image: zaktales/yolo-backend:v1.0.3
    ports:
      - "5000:5000"
    env_file:
     - ./backend/.env
    networks:
      - yolo_net
    volumes:
      - yolovol:/var/lib/docker/volumes/yolovol/_data
  client:
    image: zaktales/yolo-client:v1.0.3
    ports:
      - "3000:3000"
    networks:
      - yolo_net
    volumes:
      - yolovol:/var/lib/docker/volumes/yolovol/_data
    depends_on:
      - server
    stdin_open: true
networks:
  yolo_net:
volumes:
  yolovol: