apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    appName: yolobackend
    serverClass: backend
spec:
  selector:
    matchLabels:
      app: yolo-backend
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: yolo-backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: yolo-backend
          image: zaktales/yolo-backend:v1.0.3
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: server-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard