---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client
  annotations:
    description: "Creates client service to expose port 3000"
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000