---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: yolo-client
    component: frontend
  annotations:
    description: "Client service"
spec:
  type: LoadBalancer
  selector:
    app: yolo-client
    component: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    appName: yolo
    serverClass : client
    memoryOptimised : "yes"
    component: frontend
  annotations:
    description: "Deploying the Yolo frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      appName : yolo
      memoryOptimised : "yes" 
      app: yolo-client
      component: frontend
  template:
    metadata:
      labels:
        appName : yolo
        memoryOptimised : "yes"
        app: yolo-client
        component: frontend
    spec:
      containers:
        - name: client
          image: zaktales/yolo-client:v1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 